### ISSUE TITLE
Release version tags needed

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/stm-spirit1-rf-driver#2]
`mbed-cli` has started supporting release versions now, it would be neat if this repo would also have release tags.

`mbed releases -r` 

```
C:\Users\jankii01\mbed\mbed-os-example-client\easy-connect>mbed releases -r
easy-connect (#522e43fa1bba, tags: v1.0.0)
| * v1.0.0  <- current
|- atmel-rf-driver (#2cd9abba3e37)
|    * v0.0.10
|    * v0.0.11
|    * v0.0.12
|    * v0.0.13
|    * v0.0.14
|    * v0.0.15
|    * v0.0.16
|    * v0.0.18
|    * v0.0.19
|    * v0.0.20
|    * v0.0.21
|    * v0.0.22
|    * v0.0.23
|    * v0.0.24
|    * v0.0.25
|    * v0.0.8
|    * v0.0.9
|    * v1.0.0
|    * v1.0.1
|    * v1.0.2
|    * v1.0.3
|    * v2.0.0
|    * v2.0.1
|    * v2.0.2
|    * v2.0.3
|    * v2.1.0
|    * v2.1.1
|    * v3.0.0
|    * v3.0.1
|    * v3.0.2
|- esp8266-driver (#a7245780485c)
|    * v1.0
|    * v1.1
|    * v1.2
|    * v1.3
|    * v1.4
|- mcr20a-rf-driver (#9aac10474702)
|    No release tags detected
|- stm-spirit1-rf-driver (#0ff4ca7537f0)
|    No release tags detected
`- wifi-x-nucleo-idw01m1 (#537b01c4a053)
     No release tags detected
```

**Comment by betzw** [comment]
In order to save me some time in searching, could you pls. provide me with a link to a description on how to add _release tags_?
Or are these just _Git_ tags in a special format?

**Comment by JanneKiiskila** [comment]
They are just git tags, you can just put them in as v1.0.0 or vx.y.z.

**Comment by betzw** [comment]
OK, I have added them.
Btw, I first tried to add some of the form `v1.0.0-rc1` but it seemed not to work ... would be nice to have.

**Comment by JanneKiiskila** [comment]
I would recommend then raising an issue to [mbed-cli](https://github.com/ARMmbed/mbed-cli/issues) repo. @screamerbg

**Comment by betzw** [comment]
@JanneKiiskila, can we close this issue?

**Comment by JanneKiiskila** [comment]
https://github.com/ARMmbed/stm-spirit1-rf-driver/tree/v1.0.0 -> yes.

**Comment by JanneKiiskila** [comment]
Thank you for the support @betzw !
