### ISSUE TITLE
Nanostack and subgig 6lowpan

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/stm-spirit1-rf-driver#4]
I realize this repo is marked as a prototype.

However, I'm curious if the team is making any headway on this.

Any particularly interesting pitfalls or considerations?

Would be nice to see support for a subgig 'soc' like [ADUCRF101](http://www.analog.com/en/products/processors-dsp/microcontrollers/precision-microcontrollers/aducrf101.html#product-overview)

ADUCRF101 is missing ethernet though I suppose.

**Comment by betzw** [comment]
> I realize this repo is marked as a prototype.
> However, I'm curious if the team is making any headway on this.
> Any particularly interesting pitfalls or considerations?

At this very moment there are no known issues.
This driver is still marked as prototype as it does not support all features available with the SPSGRF-868 module mounted on top of the X-NUCLEO-IDS01A4 expansion board. It is mainly intended to be used together with the mbed 6LoWPAN Nanostack, but obviously can be used in different contexts as long as the not yet supported features are not required.

> Would be nice to see support for a subgig 'soc' like ADUCRF101

This is not within the scope of this driver as this one is meant only to support the Spirit sub-1 GHz transceiver family of STMicroelectronics.

**Comment by betzw** [comment]
In case you do not have any further concerns, could you pls. close this issue.
Otherwise, pls. let me know!
